spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:belog;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

server:
  port: 0
