spring:
  application:
    name: belog
  jpa:
    open-in-view: false

  web:
    error:
      include-exception: false
      include-message: never
      include-binding-errors: never
      include-stacktrace: never

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  shutdown: graceful
