package org.com.belog.notification.domain

enum class NotificationType(
    val requiresTargetId: Boolean = true,
) {
    GROUP_MEMBER_JOINED,
    GROUP_DELETED(requiresTargetId = false),
    MEETING_PROPOSED,
    DATE_POLL_STARTED,
    DATE_POLL_RESPONDED,
    DATE_POLL_REMINDER,
    MEETING_DATE_CONFIRMED,
    PRE_LOG_PLAN_CREATED,
    PRE_LOG_PLAN_LIKED,
    SETTLEMENT_REQUESTED,
    BILL_REGISTERED,
    SETTLEMENT_COMPLETED,
    SETTLEMENT_REMINDER,
    POST_LOG_PHOTOS_REGISTERED,
    POST_LOG_REVIEW_CREATED,
    MEETING_D7_REMINDER,
    PRE_LOG_D2_REMINDER,
    POST_LOG_TODAY_REMINDER,
    GROUP_INACTIVE_60_DAYS,
}
