package org.com.belog.notification.config

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(NotificationOutboxWorkerProperties::class)
class NotificationOutboxWorkerConfig
